'use server'

// Server actions for Auto Reports module
// Generates EOD summary from all modules + sends to Telegram + logs result

import { revalidatePath } from 'next/cache'
import { format } from 'date-fns'
import { createAdminClient } from '@/lib/supabase/server'
import { sendMessage } from '@/lib/telegram'

function revalidateReports() {
  revalidatePath('/vi/reports')
  revalidatePath('/en/reports')
}

interface EodData {
  briefingDone: number
  devTasksDone: number
  tradingWins: number
  tradingLosses: number
  tradingPnl: number
  learningCount: number
  wpOffline: number
}

// Fetch today's data across all 7 modules
async function fetchEodData(today: string): Promise<EodData> {
  const supabase = createAdminClient()

  const [briefing, devTasks, trading, learning, wp] = await Promise.all([
    supabase.from('briefing_tasks').select('status').eq('task_date', today),
    supabase.from('dev_tasks').select('status').eq('status', 'done'),
    supabase.from('trading_entries').select('result, pnl').eq('entry_date', today),
    supabase.from('learning_entries').select('id').eq('entry_date', today),
    supabase.from('wordpress_sites').select('last_status').eq('last_status', 'offline'),
  ])

  const briefingDone = (briefing.data ?? []).filter((t) => t.status === 'done').length
  const devTasksDone = (devTasks.data ?? []).length
  const tradesData   = trading.data ?? []
  const tradingWins  = tradesData.filter((t) => t.result === 'win').length
  const tradingLosses = tradesData.filter((t) => t.result === 'loss').length
  const tradingPnl   = tradesData.reduce((sum, t) => sum + (Number(t.pnl) || 0), 0)
  const learningCount = (learning.data ?? []).length
  const wpOffline    = (wp.data ?? []).length

  return { briefingDone, devTasksDone, tradingWins, tradingLosses, tradingPnl, learningCount, wpOffline }
}

// Format EOD report as plain text for Telegram
function formatEodReport(data: EodData, today: string): string {
  const pnlSign = data.tradingPnl >= 0 ? '+' : ''
  const wpAlert = data.wpOffline > 0 ? `\n⚠️ WP sites offline: ${data.wpOffline}` : ''

  return `📊 EOD Report — ${today}

✅ Briefing tasks done: ${data.briefingDone}
💻 Dev tasks done: ${data.devTasksDone}
📈 Trading: ${data.tradingWins}W/${data.tradingLosses}L (${pnlSign}${data.tradingPnl.toFixed(2)} USD)
📚 Learning entries: ${data.learningCount}${wpAlert}

Generated by per-cc`
}

// Generate EOD report: fetch data, send Telegram, log result
export async function generateEodReport(): Promise<{ success: boolean; summary?: string; error?: string }> {
  const today   = format(new Date(), 'yyyy-MM-dd')
  const supabase = createAdminClient()

  let status: 'sent' | 'failed' | 'skipped' = 'skipped'
  let errorMsg: string | null = null
  let summary: string | null = null

  try {
    const data = await fetchEodData(today)
    summary = formatEodReport(data, today)

    const chatId = process.env.TELEGRAM_CHAT_ID
    if (chatId) {
      await sendMessage(chatId, summary)
      status = 'sent'
    } else {
      // No Telegram configured — just show the report in UI
      status = 'skipped'
    }
  } catch (err) {
    status = 'failed'
    errorMsg = err instanceof Error ? err.message : 'Unknown error'
  }

  // Log the result
  await supabase.from('notification_logs').insert({
    channel:     'telegram',
    notif_type:  'eod_report',
    payload:     { summary },
    status,
    error_msg:   errorMsg,
  })

  revalidateReports()

  if (status === 'failed') return { success: false, error: errorMsg ?? 'Report failed' }
  return { success: true, summary: summary ?? '' }
}
